services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    region: oregon  # Change this if needed
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_OWNER_ID
        sync: false
